SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\Cast
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=R8051XC2
SET CPU_VENDOR=CAST, Inc.
SET UV2_TARGET=CA51F
SET CPU_XTAL=0x016E3600
"C:\Keil_v5\C51\BIN\A51.EXE" @".\hex\STARTUP._ia"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\aip3368.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\aip3368h_display.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\pin_level_scan.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\uart.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\timer0.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\timer1.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\main.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\delay.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\system_clock.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\flash.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\ca51f3xsfr.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\uart_process_data_packets.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\ui.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\user_debug.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\hex\engine_speed_scan.__i"
"C:\Keil_v5\C51\BIN\LX51.EXE" @".\hex\project.lnp"
"C:\Keil_v5\C51\BIN\OHX51.EXE" ".\hex\project" HEX
